---
title: "Notes"
author: "Michiel van Dijk"
date: "2022-09-07"
output: pdf_document
---

# Need to investige the size of the weights, which can be very large for some hh. survey package has a trimWeights function that we can use.

# It appears that at least in Balochistan - Pakistan, reweigting without m15 category results in downward scaling of childred, which puts a downward bias on income and poverty in the base year => probably best to reweigh base year including m15 and then drop this category. It also would be interesting to compare weighting in and ex m15 for all periods and scenarios. Perhaps in high-pop scenarios (SSP3), keeping the m15 category is better.

https://r-project.ro/conference2021/presentations/Inequality%20measures%20for%20weighted%20data.pdf present an example of bootstrapping inequality index. Can we provide bootrap values for outcome indicators? https://projecteuclid-org.ezproxy.library.wur.nl/journals/statistics-surveys/volume-10/issue-none/A-survey-of-bootstrap-methods-in-finite-population-sampling/10.1214/16-SS113.full  provides an overview of bootstrap methods for surveys. Which are applied in this package: https://bschneidr.github.io/svrep/. See https://cran.r-project.org/web/views/OfficialStatistics.html for a range of packages for bootstrapping, weighting etc of surveys.

See https://cran.r-project.org/web/packages/surveysd/vignettes/ipf.html for another package that is able to do household and person weighting!!! And bootsrapping!


# Functions to add in the package

-   Function that checks consistency of the person and hh data - see checks in script.
- Update create_weights_plot and improve loop in script


# Settings

Need to create a standard script to prepare the adm map, which uses adm_code and adm_name, not referring to the adm level


# Data
- need to split off mgr and tech when processing DHS and creating the dhs_db not in ssid scripts
- line 538 create subnational age_sex_projections: seem to use two names for agr-otherlows: agri_lowsk", "ag_othlowsk. Need to harmonize!. Even better would be to split this in agri and elementary as we do in the ML exercise.
- Preparation of national data in create_ssp_subnat_projections can be done in microsim_db repo. Better to create several global datasets, which serve as input data.
- # Calculate index
- CHeck that For a very small number of adms the ssp base year values are 0 (e.g. no urban population)
while future values are non-zero (e.g urbanization starting in 2030). This creates problems as the index number cannot be calculated. We solve this by now by setting the projections to 1 for all years in the adms where this happens. This ensures that the index is 1 throughout, base year values of the projections will be the same as the base year value and series are consistent. => check if we can turn this into a function.

NB: need to be clear how we allocate self-employed family farmers.
I would argue they are included ag_othlowsk in this case as this category captures this
But it is not clear how they are counted in other data pieces.

Check calculation of hh heads and why it differs so much in some regions (see BGD)

# Food conversion
Headey, Ecker Comstock convert everything to 2500 kcal adult equivalent (ae) instead of mae or fae, which we do. ae is also used in EAT-Lancet and hence is the better reference => need to update! Also check undernourishment estimation of FAO. What is the basis?

# National occupation projections.
- Need to update to more recent base year => Need to make adjustment in code where
subnational occ projections are calculated to ensure base year index is calculated correctly. apply a fix in Uganda now.
- At the moment not_in_lf is sum of unemployed and not_in_lf. Question remains what we do with labor force participation rare and employment assumptions over time.

# Consistency

Need to rename occ to occupation in occ projections as this is the header we also use in per_db!


# Methodology
- Can we calculate the headship rate from the LSMS at the adm1, if LSMS is representative at adm1?
- Check consistency between real population and that implied by simulation (hh_weight x hh_size): See note in simulate_income_change.R Also check calculation of hh_size!!
- Check contribution of not_in_lf to income change. Now we estimate wage and add but perhaps set to zero contribution simular to m15?
- Can use capital and land rents to update residual income change.

# Indicators

- Calculate poverty headcount per adm2 and per urban/rural
- Create maps of poverty headcount total, urban/rural
- Create bar chart of poverty headcount/change per adm2
- Select examplatory regions (one with large transition from rural to urban? or one with bigest change in pov)

# Selection of adm map
- Always add adm2 and adm1 even if it is dummy. At the moment the preparation of subnational benchmark assumes there is an adm2 level, should use "adm" as standard for the adm level at which the model is run, with the option of adding an "adm1" which can be used to subsample from in case of a large survey
- What determines the adm map? If a hh survey is represenatative at an adm level that is comparable to the target adm than the survey is guiding. If not any map can do, maybe best is IPUMS as this is a key data source?


# Treatment of outliers
- Check what others do (e.g. cut of rates 600/65000 kcal at hh level - see Ecker and comstock papers)
- World Bank approach
=> coded iqr and quantile methods and used first to process calorie data


# Treatment of missing data
- Zeros in consumption data in 7 day recall. Ecker assumes this is not realistic and imputs

# Regression analysis
- rethink how they are done. If intercept is large in comparison to occupation coefficients, do they largely determine growth in hh income as they grow proportionally with occupation income, or is this okay?

# Check of weights. 
- Literature of trimming weights in microsim. Need to check if resulting weights are realistic.
- Also need to check if one EA does not dominate results. Not desirable to have high weights from only a few EA obeservations.


# Checking
Need to create a script that checks all data, including:
- share of urban/rural in seed, in line with nat stat
- share of occupations in seed, idem
- share of age in seed, idem

- share of urban/rural in benchmark, in line with nat stat
- share of occupations in benchmark, idem
- share of age in benchmark, idem

- If seed is consistent with benchmark, e.g. if there are rural households when bencmark says there are rural households in a large city such as addis.


# Validation
- Compare projections to historical if panel data (e.g. Malawi) is available
- Compare different type of projections/nowcasting: (1) using average GDP such as in Lakner/WB; (2) using MAGNET wage rates


Check: The Distributional Impact of Taxes and Social Spending in Bhutan An Application with Limited Income Data, Juan Pablo Baquero
Jia Gao Yeon Soo Kim for a better method to decompose household income into occupation classes contrubibution
