#' ipu_subnat_proj
#'
#' @description
#' Function to rake subnational population projections so that they match national age-sex and
#' subnational pop projections.
#'
#' @details
#'
#' @param y Year
#' @param scen Scenario
#' @param param ssid_par
#' @param verbose Print iteration details and worst marginal stats upon completion generated by `ipfr::ipu_matrix`?
#' Default TRUE.
#'
#' @return
#' @export
#'
#' @examples
ipu_subnat_proj <- function(y, scen, adm, verbose = TRUE) {
  p() # To display progress bar in combination with furrr and progressr
  cat(y, scen, "\n")
  m <- subnat_age_sex_proj %>%
    dplyr::mutate(adm_code = paste0("x", adm_code)) %>%
    dplyr::filter(year == y, scenario == scen) %>%
    dplyr::mutate(id = paste(age, sex, sep = "x")) %>%
    dplyr::select(adm_code, id, value) %>%
    dplyr::arrange(adm_code, id) %>%
    tidyr::pivot_wider(names_from = id, values_from = value, values_fill = 0) %>%
    tibble::column_to_rownames("adm_code") %>%
    dplyr::rename(paste("adm", param$adm_level) = adm_code)

  m <- as.matrix(m)

  row_t <- subnat_urban_rural_proj %>%
    dplyr::rename(adm_code = paste("adm", param$adm_level)) %>%
    mutate(adm_code = paste0("x", adm_code)) %>%
    filter(year == y, scenario == scen) %>%
    group_by(year, scenario, adm1_name, adm1_code, adm2_name, adm2_code) %>% # Can we do this only adm_code?
    summarize(value = sum(value, na.rm = TRUE), .groups = "drop") %>%
    mutate(source = "urban_rural") %>%
    arrange(adm2_code) %>%
    pull(value)

  col_t <- nat_age_sex_proj %>%
    filter(year == y, scenario == scen) %>%
    mutate(id = paste(age, sex, sep = "_")) %>%
    arrange(id) %>%
    pull(value)

  raked_m <- ipfr::ipu_matrix(m, row_t, col_t, verbose = verbose)
  raked_m <- as.data.frame(raked_m) %>%
    rownames_to_column("adm2_code") %>%
    pivot_longer(-adm2_code, names_to = "id", values_to = "value") %>%
    separate(id, into = c("age", "sex"), sep = "x") %>%
    mutate(year = y, scenario = scen,
           adm2_code = gsub("x", "", adm2_code))
  return(raked_m)
}
